"""Stable HTTP header names at the Memory/Model Gateway boundary."""

MODEL_GATEWAY_ROUTE_HEADER = "X-Model-Gateway-Route"
MODEL_GATEWAY_DEPLOYMENT_HEADER = "X-Model-Gateway-Deployment"
MODEL_GATEWAY_CONNECTION_HEADER = "X-Model-Gateway-Connection"
MODEL_GATEWAY_CHANNEL_OPERATOR_HEADER = "X-Model-Gateway-Channel-Operator"
MODEL_GATEWAY_MODEL_AUTHOR_HEADER = "X-Model-Gateway-Model-Author"
MODEL_GATEWAY_VENDOR_HEADER = "X-Model-Gateway-Vendor"
MODEL_GATEWAY_UPSTREAM_MODEL_HEADER = "X-Model-Gateway-Upstream-Model"
MODEL_GATEWAY_ATTEMPTS_HEADER = "X-Model-Gateway-Attempts"
MODEL_GATEWAY_PRICING_HEADER = "X-Model-Gateway-Pricing"
MODEL_GATEWAY_EMBEDDING_SPACE_HEADER = "X-Model-Gateway-Embedding-Space"
MODEL_GATEWAY_EMBEDDING_DIMENSIONS_HEADER = "X-Model-Gateway-Embedding-Dimensions"
MODEL_GATEWAY_USAGE_EVENT_ID_HEADER = "X-Model-Gateway-Usage-Event-Id"
MODEL_GATEWAY_USAGE_LEDGER_STATUS_HEADER = "X-Model-Gateway-Usage-Ledger-Status"

MODEL_GATEWAY_CORRELATION_HEADER = "X-Model-Gateway-Correlation-ID"
MODEL_GATEWAY_OPERATION_HEADER = "X-Model-Gateway-Operation"
MODEL_GATEWAY_USER_TAG_HEADER = "X-Model-Gateway-User-Tag"
MODEL_GATEWAY_PREFERRED_DEPLOYMENT_HEADER = "X-Model-Gateway-Preferred-Deployment"
MODEL_GATEWAY_REQUIRE_DEPLOYMENT_HEADER = "X-Model-Gateway-Require-Deployment"
MODEL_GATEWAY_REASONING_ORIGIN_DEPLOYMENT_HEADER = (
    "X-Model-Gateway-Reasoning-Origin-Deployment"
)

MODEL_GATEWAY_ATTRIBUTION_RESPONSE_HEADERS: frozenset[str] = frozenset(
    {
        MODEL_GATEWAY_ROUTE_HEADER,
        MODEL_GATEWAY_DEPLOYMENT_HEADER,
        MODEL_GATEWAY_CONNECTION_HEADER,
        MODEL_GATEWAY_CHANNEL_OPERATOR_HEADER,
        MODEL_GATEWAY_MODEL_AUTHOR_HEADER,
        MODEL_GATEWAY_VENDOR_HEADER,
        MODEL_GATEWAY_UPSTREAM_MODEL_HEADER,
        MODEL_GATEWAY_ATTEMPTS_HEADER,
        MODEL_GATEWAY_PRICING_HEADER,
        MODEL_GATEWAY_EMBEDDING_SPACE_HEADER,
        MODEL_GATEWAY_EMBEDDING_DIMENSIONS_HEADER,
        MODEL_GATEWAY_USAGE_EVENT_ID_HEADER,
        MODEL_GATEWAY_CORRELATION_HEADER,
        MODEL_GATEWAY_USAGE_LEDGER_STATUS_HEADER,
    }
)

__all__ = [
    "MODEL_GATEWAY_ATTEMPTS_HEADER",
    "MODEL_GATEWAY_ATTRIBUTION_RESPONSE_HEADERS",
    "MODEL_GATEWAY_CHANNEL_OPERATOR_HEADER",
    "MODEL_GATEWAY_CONNECTION_HEADER",
    "MODEL_GATEWAY_CORRELATION_HEADER",
    "MODEL_GATEWAY_DEPLOYMENT_HEADER",
    "MODEL_GATEWAY_EMBEDDING_DIMENSIONS_HEADER",
    "MODEL_GATEWAY_EMBEDDING_SPACE_HEADER",
    "MODEL_GATEWAY_MODEL_AUTHOR_HEADER",
    "MODEL_GATEWAY_OPERATION_HEADER",
    "MODEL_GATEWAY_PREFERRED_DEPLOYMENT_HEADER",
    "MODEL_GATEWAY_PRICING_HEADER",
    "MODEL_GATEWAY_REASONING_ORIGIN_DEPLOYMENT_HEADER",
    "MODEL_GATEWAY_REQUIRE_DEPLOYMENT_HEADER",
    "MODEL_GATEWAY_ROUTE_HEADER",
    "MODEL_GATEWAY_UPSTREAM_MODEL_HEADER",
    "MODEL_GATEWAY_USAGE_EVENT_ID_HEADER",
    "MODEL_GATEWAY_USAGE_LEDGER_STATUS_HEADER",
    "MODEL_GATEWAY_USER_TAG_HEADER",
    "MODEL_GATEWAY_VENDOR_HEADER",
]
