"""Column ensure helpers and migration runner for memory.db."""
from __future__ import annotations

import sqlite3
from typing import TYPE_CHECKING, Any

from app.schema_migrations import apply_schema_migrations

if TYPE_CHECKING:
    from app.memory.store._monolith import MemoryStore

def _ensure_memories_usage_columns(connection: sqlite3.Connection) -> None:
    columns = {
        row["name"] for row in connection.execute("PRAGMA table_info(memories)").fetchall()
    }
    if "last_used_at" not in columns:
        connection.execute("ALTER TABLE memories ADD COLUMN last_used_at TEXT")
    if "usage_count" not in columns:
        connection.execute("ALTER TABLE memories ADD COLUMN usage_count REAL DEFAULT 0.0")
    if "valence" not in columns:
        connection.execute("ALTER TABLE memories ADD COLUMN valence REAL DEFAULT 0.5")
    if "arousal" not in columns:
        connection.execute("ALTER TABLE memories ADD COLUMN arousal REAL DEFAULT 0.3")
    if "stability" not in columns:
        connection.execute("ALTER TABLE memories ADD COLUMN stability TEXT DEFAULT 'stable'")
    if "valid_from" not in columns:
        connection.execute("ALTER TABLE memories ADD COLUMN valid_from TEXT")
    if "valid_until" not in columns:
        connection.execute("ALTER TABLE memories ADD COLUMN valid_until TEXT")
    if "review_after" not in columns:
        connection.execute("ALTER TABLE memories ADD COLUMN review_after TEXT")
    if "sensitivity" not in columns:
        connection.execute("ALTER TABLE memories ADD COLUMN sensitivity TEXT DEFAULT 'normal'")
    if "origin" not in columns:
        connection.execute(
            "ALTER TABLE memories ADD COLUMN origin TEXT DEFAULT 'user_asserted'"
        )
    if "evidence_memory_ids_json" not in columns:
        connection.execute("ALTER TABLE memories ADD COLUMN evidence_memory_ids_json TEXT")
    if "topics_json" not in columns:
        connection.execute("ALTER TABLE memories ADD COLUMN topics_json TEXT")
    if "entities_json" not in columns:
        connection.execute("ALTER TABLE memories ADD COLUMN entities_json TEXT")
    if "archived_at" not in columns:
        connection.execute("ALTER TABLE memories ADD COLUMN archived_at TEXT")
    if "temporal_subject" not in columns:
        connection.execute("ALTER TABLE memories ADD COLUMN temporal_subject TEXT")
    if "temporal_predicate" not in columns:
        connection.execute("ALTER TABLE memories ADD COLUMN temporal_predicate TEXT")
    if "status" not in columns:
        connection.execute("ALTER TABLE memories ADD COLUMN status TEXT DEFAULT 'dynamic'")
    if "digested" not in columns:
        connection.execute("ALTER TABLE memories ADD COLUMN digested INTEGER DEFAULT 0")
    if "decay_lambda" not in columns:
        connection.execute("ALTER TABLE memories ADD COLUMN decay_lambda REAL")
    if "supersedes" not in columns:
        connection.execute("ALTER TABLE memories ADD COLUMN supersedes TEXT")
    if "superseded_by" not in columns:
        connection.execute("ALTER TABLE memories ADD COLUMN superseded_by TEXT")
    connection.execute(
        """
        UPDATE memories
        SET origin = 'agent_derived'
        WHERE source_message IN (
            'digest_memories:reflection',
            'digest_memories:feel'
        )
        """
    )

    connection.execute(
        """
        UPDATE memories
        SET status = 'dynamic'
        WHERE status IS NULL OR status = ''
        """
    )
    connection.execute(
        """
        UPDATE memories
        SET origin = 'user_asserted'
        WHERE origin IS NULL OR origin = ''
        """
    )
    connection.execute(
        """
        UPDATE memories
        SET type = 'semantic'
        WHERE type IS NULL
           OR type = ''
           OR type IN (
               'project', 'preference', 'fact', 'learning',
               'style', 'person', 'relationship'
           )
           OR type NOT IN (
               'episodic', 'semantic', 'procedural',
               'emotional', 'reflective'
           )
        """
    )


def _ensure_memories_embedding_space_column(connection: sqlite3.Connection) -> None:
    columns = {
        row["name"]
        for row in connection.execute("PRAGMA table_info(memories)").fetchall()
    }
    if "embedding_space_id" not in columns:
        # Existing vectors intentionally remain unidentified. Inferring a
        # space from the current model or dimensions could mix vectors
        # generated by a previous provider/model configuration.
        connection.execute(
            "ALTER TABLE memories ADD COLUMN embedding_space_id TEXT"
        )


def _ensure_revision_columns(connection: sqlite3.Connection) -> None:
    for table_name in (
        "memories",
        "core_memory_sections",
        "core_memory_section_history",
    ):
        columns = {
            str(row["name"])
            for row in connection.execute(
                f"PRAGMA table_info({table_name})"
            ).fetchall()
        }
        if not columns:
            continue
        if "revision" not in columns:
            connection.execute(
                f"ALTER TABLE {table_name} "
                "ADD COLUMN revision INTEGER NOT NULL DEFAULT 1"
            )
        connection.execute(
            f"UPDATE {table_name} SET revision = 1 "
            "WHERE revision IS NULL OR revision < 1"
        )


def _run_migrations(connection: sqlite3.Connection) -> None:
    """按 PRAGMA user_version 顺序执行一次性的 schema/数据迁移。

    建表语句保持幂等并在每次启动执行；迁移只运行尚未应用的版本，
    避免老库每次启动都重复全表 UPDATE 回填。
    """
    # Resolve through the migrations module so tests can monkeypatch the list.
    from app.memory.store import migrations as migrations_mod

    apply_schema_migrations(
        connection,
        migrations_mod._MEMORY_SCHEMA_MIGRATIONS,
        schema_name="memory database",
    )


